CREATE TABLE rounds (
  id BIGSERIAL PRIMARY KEY NOT NULL,
  p1_throw VARCHAR(100) NOT NULL,
  p2_throw VARCHAR(100) NOT NULL,
  result VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp NOT NULL
);
